# Generated by Django 5.0.4 on 2024-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=30)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('grade', models.CharField(choices=[('grade6', 'grade 6'), ('grade7', 'grade 7')], max_length=50)),
                ('project', models.CharField(max_length=50)),
                ('progress', models.TextField()),
                ('hours', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('learning', models.CharField(choices=[('Active_Recall', 'Active Recall'), ('Horizontal_Learning', 'Horizontal Learning'), ('Vertical_Learning', 'Vertical Learning')], max_length=50)),
                ('how', models.TextField()),
            ],
        ),
    ]
