# Generated by Django 5.0.4 on 2024-04-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
