# Generated by Django 5.0.4 on 2024-04-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='grade',
            field=models.CharField(choices=[('grade 7', 'grade 6'), ('grade 7', 'grade 7')], max_length=50),
        ),
    ]
